[theme]
primaryColor = "#0D9488"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#13263C"
font = "sans serif"
[server]
maxUploadSize = 20
[browser]
gatherUsageStats = false
